---
title: "clinical_and _transcrip_data"
format: html
editor: visual
---
### References
Main reference for obtain data and the TNBC classification: 
https://doi.org/10.1038/s41467-021-26502-6
"Multi-omics analysis identifies therapeutic vulnerabilities in triple-negative 
breast cancer subtypes"
https://github.com/TransBioInfoLab/TNBC_analysis/tree/master

## Load required packgaes

```{r}
library(dplyr)
library(TCGAbiolinks)
```


## Download clinical and transcriptomic data

```{r}
BRCA.htseq_counts = read.table(file = "TCGA-BRCA.htseq_counts.tsv",
                               sep = "\t",
                               header = T,
                               row.names = 1)

BRCA.htseq_counts_round = round(((2 ^ BRCA.htseq_counts) - 1), 0)

query.clin <- GDCquery(project = "TCGA-BRCA",
                       data.category = "Clinical",
                       data.format = "BCR XML")

GDCdownload(query.clin)

GDCdownload(query.rna, files.per.chunk = 1 ,directory = my.dir)

BRCA.clin <- GDCprepare_clinic(query = query.clin, 
                               clinical.info = "patient")
```

